# Introduction to programming in Python

This notebook is an adaptated version of the [Introduction to Python](https://colab.research.google.com/github/Pseudomoaner/Homeworks_Incomplete/blob/main/ODE_Modelling/Introduction%20to%20Python.ipynb#scrollTo=609764b9) Google Colab Notebook.

**What to expect**

It is intended for people who are unfamiliar with programming in general, and provides a basic overview of some of the most important programming concepts as well as how they are implemented in Python.

**What we will cover**

We will focus on how to use Python and its basic tools. We will learn syntax, types of objects, variables, lists, tuples, conditionals, "for" and "while" loops, among other basic tools.

**A note for beginners**

There many things can be done in Python, here we will cover only the basics, but we will learn more advance tools in the following notebooks.

**Tip**: don't worry if you do not understand everything in the beginning. It will make more sense as we advance in the course.

# What is Python?

Python is a programming language, a way to write instructions that a computer can execute. It is syntax + rules for writing code.

1. **Widely used**. One of the most widely used programming languages together with Java. It is very well developed, offering many libraries and tools.
2. **Very flexible**. Variables are just names pointing to objects. You can change the "type" of data a variable holds whenever you want.  
3. **High-level**. Python is written in C, where you need to write a lot of code for doing something simple. Python simplifies C functions, allowing you to write code faster.
4. **General-purpose**. You can do almost everything in Python. It allows manipulating data, run analysis, build models, automate workflows.
5. **Dynamic programming language**. Code is interpreted at run-time. No need to compile, then you find code errors faster, which enhances development speed.

## Where does Python run?

Before we dive into coding, it is important to understand that Python can live in two primary "homes." Throughout this course, we will focus on Remote execution, but knowing the full landscape will help you as you grow as a developer.

1. **Locally (on your computer)**

Running Python locally means the code uses your computer’s hardware (CPU, RAM). There are two main ways to set this up:

*   The "Lite" Way: Installing Python directly from [python.org](https://www.python.org/downloads/). This gives you the engine, but you'll need to provide your own tools to write the code.

*   The "Toolbox" Way ([Anaconda](https://www.anaconda.com/download)): Anaconda is a distribution that bundles Python with popular data science libraries and tools like Jupyter Notebooks. It’s like buying a fully-stocked workshop instead of just a hammer.

Where do you type the code?
For larger projects, developers use IDEs (Integrated Development Environments) like [VS Code](https://code.visualstudio.com/) or PyCharm. Think of an IDE as "Microsoft Word for code", it helps with spell-check (debugging), autocompletion, and organizing files.

2. **Remotely (in the cloud)**

Remote environments allow you to write and run code in your web browser. The code actually executes on a powerful server elsewhere (like a Google data center), not on your laptop.

Online Interpreters: Sites like Replit or PythonAnywhere are great for quick tests without any setup.

[Google Colab](https://colab.research.google.com/#scrollTo=GJBs_flRovLc) **(our choice)**: This is a "Notebook" environment. It allows us to mix code, text, and images in a "storytelling" format. It also gives us access to Google’s powerful computers for free.

**Our Path**: We will be working remotely Google Colab notebooks for the duration of this course unless otherwise specified. This ensures everyone has the same setup and no one has to worry about installation errors!

### Print function

The most basic built-in function

In [8]:
print('hello world')

hello world


## Arithmetic manipulations (use Python as calculator)

Probably the most basic use of Python is as a calculator. Simply inputting arithmetic expressions will cause it to return the answers to those expressions:

In [15]:
1 + 1

4

As well as the standard operators (+, -, /, *), Python also provides a couple of more specialised operators: exponentiation (e.g. $2^4$) is written with a double asterisk:

In [ ]:
2**4

16

The remainder of a division operation is written with the % sign:

In [ ]:
33 % 9

6

And the floor of a division (the result of the division ignoring the remainder) is given via a double backslash, //:

In [ ]:
33 // 9

3

## Variables and types

Rather than writing the numbers out directly in these calculations, we can instead define variables and use these instead:

In [ ]:
# simple integer assignments
a = 3
b = 4

a*b

12

You can view a variable as a human-readable tag that points to something in the computer's memory. In this case, this 'something' was two integers, but in general variables can represent anything from text to a whole simulation.

The different kinds of data that a variable can represent are denoted by their type. Some important types include:
- Integers (int): Whole numbers (e.g., 10, -5)
- Floating point numbers (float): Real numbers, in decimal representation (e.g. 3.14)
- Boolean truth values (bool): True or False, typically the result of comparison operations (e.g. 1 < 3 results in True)
- Complex: Numbers with real and imaginary parts (e.g., 2+3j)
- Strings (str): Text

You can check the type of a variable by using the type() command. For example,

In [ ]:
a = 1.5
b = '1.5' #Quote marks indicate that the contents will be interpreted as a string

print(type(a))
print(type(b))

<class 'float'>
<class 'str'>


In general, the result of operations on variables depends on their type, and in many cases an operation will result in an error if an input variable is of the wrong type:

In [ ]:
print(a * 3)
print(a / 3)
print(b * 3) #When applied to strings, the * operator concatenates multiple copies of that string together
print(b / 3) #Results in an error, as the / operator is not defined for strings

4.5
0.5
1.51.51.5


TypeError: unsupported operand type(s) for /: 'str' and 'int'

You can also change data from one type to another by **casting** it:

In [ ]:
b = '1.5 '

print(b * 3)
print(float(b) * 3) #Casting b to float means the multiplication operation treats it as a floating point number

Not every type of cast is well defined. For example, if we try to convert the string '1.5' to an integer, we get an error:

In [ ]:
print(int(b) * 3)

However, the float to int cast is well defined (floating point numbers are rounded to the nearest integer), so we could chain together casts to get a valid output:

In [ ]:
print(int(float(b)) * 3)

### Boolean types and truth testing

In [6]:
# A boolean takes on only the values True or False
enjoying_tutorial = True
b1 = False

type(enjoying_tutorial)

bool

In [9]:
a = -3 # variable assignment
a < 0 # boolean evaluation
a > 0 # boolean evaluation

False

In [ ]:
# objects identical?
l1 = l2 = [1,2]

l1 is l2

## Data structures

Most code requires more complex objects built out of basic data types. Python provides built-in functions for many common structures, such as lists, strings, tuples, range, dict, set, frozenset. Many additional structures can be found in the collections [module](https://docs.python.org/3/library/collections.html).

### Strings

Immutable sequences of Unicode characters

In [62]:
my_string = str('') #or just my_string = ''

print(type(my_string), 'empty string:', str('')) # empty string

<class 'str'> empty string: 


In [68]:
s = "hello world"
len(my_string) # cound number of characters in string

11

In [69]:
# replace a substring in a string with something else
s2 = s.replace("world", "test")
print(s2)

hello test


In [70]:
#We can index a character in a string using `[]`:

s2[0]

'h'

In [72]:
# we can print part of the string
print(s[2:5]) # from the 2th caraccter to 5th
print(s[6:]) # from the 6th caraccter to the end

llo
world


In [73]:
# We can also define the step size using the syntax `[start:end:step]`, default step is 1
# This technique is called slicing. Read more about the syntax here: http://docs.python.org/release/2.7.3/library/functions.html?highlight=slice#slice

s[::2]

'hlowrd'

In [42]:
list_to_string = str([1, 2])
print(list_to_string)

[1, 2]


In [43]:
my_string2 =str('5')
print(my_string2 + 20) # 5 is not a number anymore. Thus, we cannot concatenate


TypeError: can only concatenate str (not "int") to str

In [44]:
my_string3 = 'Age: ' + 25 # we cannot concatenate either
print(my_string3)

TypeError: can only concatenate str (not "int") to str

In [46]:
my_string3 = 'Age: ' + '25' # string + string we can do
print(my_string3)

Age: 25


### Lists and Tuples

For manipulating larger amounts of data, we can make use of two different data storage objects: **Lists** and **Tuples**. Both of these allow us to store heterogeneous collection of items in an ordered sequence.

* List elements can be accessed by position. The standard syntax for creating a list is square brackets

```
list = []
```
But they can be also defined like this:
```
list = list()
```
* Tuples are inmutable lists, which means that they cannot be modified after being created. They are defined like this:

```
tuple = ()
```
    

In [75]:
# Example of a list:
exList = [1,2,3,4]

print(exList)
print(exList[0]) # Python starts counting from 0
print(exList[:3])


[1, 2, 3, 4]
[1, 2, 3]
(1, 2, 3, 4)
(3, 4)


In [76]:
# elements in a list do not have to be of the same type
l = [1, 'a', 1.0, 1-1j]
print(l)

[1, 'a', 1.0, (1-1j)]


In [77]:
#Python lists can be inhomogeneous and arbitrarily nested:

nested_list = [1, [2, [3, [4, [5]]]]]

nested_list

[1, [2, [3, [4, [5]]]]]

Lists play a very important role in Python. For example they are used in loops and other flow control structures (discussed below). There are a number of convenient functions for generating lists of various types, for example the `range` function, which produces immutable sequences of numbers typically used in loops, as we will see later.

In [80]:
start = 10
stop = 30
step = 2

print(range(start, stop, step))

# in python 3 range generates an iterator, which can be converted to a list using 'list(...)'.
# It has no effect in python 2

print(list(range(start, stop, step)))

range(10, 30, 2)
[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [84]:
s = "hello world"
list(s) #convert string to list


['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']

In [87]:
# sorting lists

s2 = list(s)
s2.sort()

print(s2) # sort aplpied to list
print(s.sort()) # sort does not work for strings directly

[' ', 'd', 'e', 'h', 'l', 'l', 'l', 'o', 'o', 'r', 'w']


AttributeError: 'str' object has no attribute 'sort'

#### Adding, inserting, modifying, and removing elements from lists

In [88]:
# create a new empty list
l = []

# add an elements using `append`
l.append("A")
l.append("d")
l.append("d")

print(l)

['A', 'd', 'd']


In [ ]:
# We can modify lists by assigning new values to elements in the list

l[1] = "p"
l[2] = "p"

print(l)

In [ ]:
l[1:3] = ["d", "d"]

print(l)

In [89]:
# Insert an element at an specific index using `insert`
l.insert(0, "i")
l.insert(1, "n")
l.insert(2, "s")
l.insert(3, "e")
l.insert(4, "r")
l.insert(5, "t")

print(l)

['i', 'n', 's', 'e', 'r', 't', 'A', 'd', 'd']


In [ ]:
# Remove first element with specific value using 'remove'

l.remove("A")

print(l)

In [90]:
# Remove an element at a specific location using `del`:
del l[7]
del l[6]

print(l)

['i', 'n', 's', 'e', 'r', 't', 'd']


### Tuples

The difference between these two storage types introduces an important concept in Python. Lists can be modified after they have been created, while tuples cannot:

In [96]:
# Example of a tuple:
exTuple = (1,2,3,4)

print(exTuple)
print(exTuple[0]) # Python starts counting from 0
print(exTuple[2:])

(1, 2, 3, 4)
1
(3, 4)


In [91]:
exList[1] = 10 #2nd element of the list exList is changed to 10
print(exList)

exTuple[1] = 10
print(exTuple)

TypeError: 'tuple' object does not support item assignment

In Pythonic jargon, we would say that lists are **mutable**, while tuples are not. This can be important for controlling what operations can be performed on specific pieces of data, especially when your code is used by other users who may not be familiar with it.

In [92]:
point = (10, 20)

print(point, type(point))

(10, 20) <class 'tuple'>


In [ ]:
point = 10, 20

print(point, type(point))

In [93]:
# We can unpack a tuple by assigning it to a comma-separated list of variables:
x, y = point

print("x =", x)
print("y =", y)

x = 10
y = 20


### Dictionaries

Dictionaries are also like lists, except that each element is a key-value pair. The syntax for dictionaries is `{key1 : value1, ...}`:

In [98]:
# A dictionary is an unordered mapping from keys to values
fruit_prices = {
    'apple': 0.65,
    'mango': 1.50,
    'strawberry': '$3/lb',
    'durian': 'unavailable' # keys can be anything
}
print(type(fruit_prices))
print(fruit_prices)

<class 'dict'>
{'apple': 0.65, 'mango': 1.5, 'strawberry': '$3/lb', 'durian': 'unavailable'}


In [111]:
# change fruit

fruit_prices['blueberry'] = fruit_prices['strawberry']
print(fruit_prices)

{'apple': 0.65, 'mango': 1.5, 'strawberry': '$3/lb', 'durian': 'unavailable', 'avocado': 200, 'fresa': '$3/lb'}


In [108]:
# add a fruit

fruit_prices['avocado'] = 1.5
print(fruit_prices)


{'apple': 0.65, 'mango': 1.5, 'strawberry': '$3/lb', 'durian': 'unavailable', 'avocado': 1.5}
1.5


In [109]:
# change prince of avodado

fruit_prices['avocado'] = 200
print(fruit_prices)

{'apple': 0.65, 'mango': 1.5, 'strawberry': '$3/lb', 'durian': 'unavailable', 'avocado': 200}


In [103]:
# What is the proce of mango and apple?

print(fruit_prices['mango'])

print(fruit_prices.get('apple')) # get() function

1.5
0.65


In [105]:
# how much would it be to buy mango and 1 lb of blueberry?
print(fruit_prices['blueberry'])
print(type(fruit_prices['blueberry']))

raw_value = fruit_prices['blueberry']
only_cost = raw_value[1]

# Convert it to an actual integer so you can do math
price_blueberry = int(only_cost)

price_mango = fruit_prices['mango']
print(price_mango + price_blueberry)

$3/lb
<class 'str'>
4.5


### Sets

Unordered collections of unique, mutable objects.

In [112]:
# Creating a set of fruits
fruits = {"apple", "banana", "cherry", "apple"}

print(fruits)
# Output: {'banana', 'cherry', 'apple'}
# Notice 'apple' only appears once!

{'banana', 'cherry', 'apple'}


In [114]:
messy_list = [1, 2, 2, 3, 4, 4, 4]
clean_set = set(messy_list) # {1, 2, 3, 4}
print(clean_set)

{1, 2, 3, 4}


In [120]:
# Set operations
group_a = {"Alice", "Bob"}
group_b = {"Bob", "Charlie"}

# Who is in both groups?
print(group_a.intersection(group_b)) # {'Bob'}
print(group_a.union(group_b)) # {'Alice', 'Bob', 'Charlie'}
print(group_a - group_b) # {'Alice'}
print(group_b - group_a) # {'Charlie'}

{'Bob'}
{'Alice', 'Charlie', 'Bob'}
{'Alice'}
{'Charlie'}


## Conditional expressions, loops and functions

To begin to build up more complex programs, we will need to get to grips with three important programming concepts:

 * At an intermediate point through a program, we may wish to execute different operations depending on its internal state without providing external intervention. To distinguish different states of the program and define the resulting sequence of operations in each case, we use **conditional expressions**.
 * In many cases, we wish to apply a particular sequence of operations multiple times. Explicitly writing out each of these repetitions would be cumbersome, and in many cases we don't know how many times to repeat the operations until we run the code. To get around these issues, we use **loops**.
 * Similarly, we may wish to apply the same sequence of operations to multiple different sets of data. Rather than explicitly write out the full set of operations each time we wish to apply them, we usually package them up into **functions**.

### Conditional expressions

Conditional expressions are the main means by which we control the flow of a program. Python has only a single type of conditional expression, the **if** statement, which is implemented almost as if writing a phrase in English:

In [ ]:
a = -3

if a < 0:
    print('a is negative') # VERY IMPORTANT! Note indentation (white space before the code statements).
else:
    print('a is positive')

The expression a < 0 evaluates to a Boolean, in this case True. This result is then used by the if statement to determine which of the following code blocks should be executed: if True, the block immediately following the 'if ...:' line is executed. If False, the block following the 'else:' expression is evaluated instead.

If we wish to distinguish between more than two possibilities, we can make use of the 'elif ...:' statement:

In [ ]:
b = 0

if b < 0:
    print('b is negative')
elif b == 0: # Note the use of the double equals sign (==), which returns True if both sides are equal.
    print('b equals 0')      #This differs from the use of the single =, which is used as the variable assignment operation.
else:
    print('b is positive')

In this case, the initial condition check (b < 0) returns False, so control flows to the next condition check (b == 0), which returns True and causes the following code block to be executed. All subsequent condition checks (in this case, the 'else:' line) are skipped.

### For loops

For loops are used when we know how many times we wish to repeat an block of code before we execute that section of the program. As an example, one (inefficient) way to multiply 2 by 4 is to add 2 to itself 4 times:

In [123]:
for x in [1,2,3]:
    print(x)

1
2
3


In [55]:
a = 2
b = 4

total = 0

for i in range(b): #i is incremented during each cycle of the loop, going through the sequence i = 0, i = 1, i = 2, ... i = (b-1)
    print(i)
    total += a #The notation x += y is equivalent to x = x + y.

print(total)

0
1
2
3
8


### While loops

While loops are used when we *do not* know how many times we wich to repeat a code block before we come to execute that section of the code. For example, one way of performing division is to count how many times you must subtract one number from another before it equals 0:

In [ ]:
a = 3
b = 18

count = 0

while b > 0: #The operation b > 0 returns a Boolean which is True as long as b is greater than 0. As soon as it switches to False, the loop terminates.
    b -= a
    count += 1

print(count)

While loops can be dangerous, as they can result in the system getting stuck if the condition they are checking can never be false. The most basic example of this would be to simply write 'while True:'.

### Function definitions

If we want to use a particular piece of code in multiple places, it is often convenient to package that piece of code up as a function. Functions take in a given number of 'arguments' and manipulate them internally, resulting in one or many outputs. We can very easily turn our multiplication example into a function:

In [11]:
def multiply(int1,int2): #int1 and int2 are inputs
    total = 0

    for i in range(int2):
        total += int1

    return total #return operation defines the output of the function

In [12]:
print(multiply(3,4))
print(multiply(9,2))

#Functions can also take in variables
a = 5 # define a variable a
b = 20 # deine a variable b
print(multiply(a,b))

12
18
100


An important idea to note here is the notion of **scope**. The scope of a particular name binding (i.e. what the variable is called) represents the part of the program in which that binding is valid.

In this case, we can see that the scope of the variables int1 and int2 is restricted to the multiply function definition - if for example we were to call other variables int1 and int2 in a different part of the code, this would have no effect on the output of this function:

In [14]:
print(multiply(3,5)) #Outputs 15

int1 = 24 # here, int1 is a variable, independent from the function multiply(int1,int2) defined above.
int2 = 15 # same for int2

print(multiply(3,5)) #Still outputs 15

15
15


### Class definition

In Python, a class is a blueprint or template for creating objects. It allows you to group data (attributes) and behaviours (methods) into a single logical unit. For example, a "Car" class might specificy that every car has a color and can drive(). The constructor __init__ is an special method that runs automatically when you create a new object. Its main job is to set the initial state (attrributes) of the object.
The self parameter is mandatory first argument for methods within a class. It refers to the specific instance of the object being worked on, allowing Python to distinguish between differenrt objects of the same class.  

Use Class for complex workflows

In [121]:
# Define class Bacteria with attributes (name, shape, gram_stain) and method (describe itself))
class Bacteria:
    microorganism_type = "Prokaryote"
    def __init__(self, name, shape, gram_stain):
        self.name = name
        self.shape = shape
        self.gram_stain = gram_stain
    def describe(self):
        return f"{self.name} is a {self.shape}-shaped, {self.gram_stain} bacterium."

In [122]:
my_bacteria = Bacteria("Escherichia coli", "rod", "Gram-negative")
print(my_bacteria.describe())

Escherichia coli is a rod-shaped, Gram-negative bacterium.


# Python libraries

So far, we have looked at Python's core functionality, the tools available within every copy of Python. However, Python's functionality can be greatly extended by importing new tools written by other developers. These tools are presented as **libraries**. There are over 500,000 libraries available for Python as of 2026!

Python libraries are primarily fetched and installed from source repositories, such as the Python Package Index ([PyPI](https://pypi.org/)) using the pip package manager, [Conda-Forge](https://conda-forge.org/) using the conda package manager (mainly for Anaconda), and [Github](https://github.com/topics/python-libraries) trough git clone commands.

We use pip to install a library in Colab by running the following code:

```
!pip install library_of_interest
```
*Notice the exclamation mark before pip. This tells Colab that this line is not Python code. It is a command for the underlying operating system (the Terminal/Shell). We use it to install new tools or interact with the computer's files directly (in a deeper level).

Colab pre-installs the most used libraries, such as Numpy. Thus, in this case, we do not need to run the code above to be able to start working with Numpy.


## Introduction to NumPy

One of the most used libraries is NumPy, a library of classes and functions designed to facilitate large-scale numerical data manipulation.

Importing new libraries is quite easy. Running the below cell will import NumPy into your current workspace:

In [18]:
import numpy as np #The 'as np' command defines how the library will be called in downstream code (a nickname for simplicity)

### The ndarray object

The core element of NumPy is the ndarray, which stands for n-dimensional array. Arrays are storage for numerical data, and include vectors (1-dimensonal arrays) and matrices (2-dimensional arrays).

Data is assigned to and read out from arrays by specifying the coordinates of the locations you want to access. The **first coordinate refers to the rows and the second to columns**:

In [24]:
testData = np.zeros((4,4)) #Initialise a 4x4 matrix (ndarray) filled with zeros

print(" ") # Separators
print(testData)
print(" ")

# Modify matrix

testData[1,2] = 3 #Assign the value 3 to row 2, column 3

print(" ")
print(testData) #Print the whole array
print(" ")
print(testData[1,2]) #Print just the modified element
print(" ")

 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
 
[[0. 0. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
 
3.0
 


You can also access multiple elements at once by specifying a range of elements in each dimension:

In [25]:
testData2 = np.zeros((4,4))

testData2[:,1] = 1 #The : indicates that all rows should be accessed

print(testData2)
print(' ')

testData2[2,:2] = 2 #Specify that the first two columns of row 2 should be accessed

print(testData2)
print(' ')

testData2[0,-1] = 3 #Can use negative indicies to count from the end of the array

print(testData2)

[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]]
 
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [2. 2. 0. 0.]
 [0. 1. 0. 0.]]
 
[[0. 1. 0. 3.]
 [0. 1. 0. 0.]
 [2. 2. 0. 0.]
 [0. 1. 0. 0.]]


Notice that Python starts counting from 0 like the Mayans!

### Manipulating arrays

NumPy provides a great many tools for manipulating this basic ndarray object. The following code illustrates some common examples - for more, see the [NumPy documentation](https://numpy.org/doc/stable/reference/index.html#reference). In general, if you can think of some way of reshaping or otherwise manipulating an array, there will be some function within NumPy that can do it already.

In [27]:
seqLst = np.arange(5) #Create a 1D ndarray containing a sequence of numbers

print(seqLst)
print(' ')

seqArray1 = np.tile(seqLst, (5,1)) #Repeat the sequence array 5x as a row

print(seqArray1)
print(' ')

seqArray2 = np.tile(seqLst, (1,5)) #Repeat the sequence array 5x as a column

print(seqArray2)
print(' ')

transArray = seqArray1.T #The transpose of the matrix represented by seqArray1. Trenspose means: rows become columns and viceversa.

print(transArray)
print(' ')

multArray = np.multiply(seqArray1,transArray) #The elementwise product of seqArray1 and its transpose

print(multArray)
print(' ')

dotProduct = np.dot(seqArray1,transArray) #The dot product multipies rows by columns and add them
print(dotProduct)

[0 1 2 3 4]
 
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
 
[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]]
 
[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
 
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
 
[[30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]
 [30 30 30 30 30]]


## Pythonic snake pits

As with any language, Python can sometimes behave in a counterintuitive way. Usually, these behaviours represent something fundamental about the way the language works, and can lead to a deeper understanding of the subject. However, at other times they can just be irritating.

There are some good articles describing some of these quirks (intermediate users may wish to see [this article](https://deepsource.io/blog/python-common-mistakes/) for an example). One particularly problematic trip hazard for users coming from other languages is the way that variable assignment works:

In [28]:
lstA = [1,2,3,4]
lstB = lstA
lstA[1] = 10

print(lstB) # modified by the change in lstA

lstB[2] = 30

print(lstA) # modified by the change in lstB

[1, 10, 3, 4]
[1, 10, 30, 4]


If you are coming from a language like Matlab, you might not have expected editing the list represented by each variable lstA and lstB to affect the other. However, when Python evaluates the expression lstB = lstA, it does not create a copy of the original list and assign it to the new variable, instead *both variables are linked to the same list*. This means that manipulation of either variable affects the other (this is one reason why immutable objects like tuples can be useful for minimising the opportunites for errors to creep in unexpectedly).

When we do need to create a separate instance of a mutable object like a list, we instead use the copy() function:

In [29]:
lstA = [1,2,3,4]
lstB = lstA.copy() # by copying the object, we do not modigy the original anymore
lstA[1] = 10

print(lstB) # now lstB is not affected by a change in lstA

lstB[2] = 30

print(lstA) # now lstA is not affected by a change in lstB

[1, 2, 3, 4]
[1, 10, 3, 4]


In NumPy, the syntax is slightly different, but the basic idea is the same:

In [30]:
arA = np.array([1,2,3,4])
arB = arA
arC = np.copy(arA)

arB[2] = 20

print(arA)
print(arB)
print(arC)

[ 1  2 20  4]
[ 1  2 20  4]
[1 2 3 4]
